let data = [
  {
    title: "Goma Dofu",
    description: "Tofu de sésamo blanco",
    portions: "Sirve entre 8 y 10 porciones",
    ingredients: [
      "500 ml (1/2 litro) de agua filtrada o de manantial",
      "Un trozo de 5 cm de kombu (opcional)",
      "50 gramos de almidón de kudzu (búscalo en tiendas de alimentos naturales o mercados japoneses, posiblemente bajo el nombre de kuzuko)",
      "70 gramos de pasta de sésamo blanco (puedes usar tahini de Oriente Medio o neri-goma japonés, lo que sea más fácil de encontrar)",
      "1 cucharada de sake (opcional)",
    ],
    image: "https://i.postimg.cc/MGMXQ31y/goma-dofu.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
    instruction: [
      "Ponga el agua y el kombu (si lo usa) en un bol y deje reposar durante al menos 1 hora. Retire el kombu y deséchelo, o resérvelo para otro uso (yo lo agrego al agua cuando cocino legumbres, se dice que ayuda a que sean más fáciles de digerir).",
      "Coloque el almidón de kudzu en un bol mediano para mezclar. Agregue un poco del agua infusionada con kombu y revuelva/triture hasta que esté completamente suave. Añada la pasta de sésamo y luego vierta el resto del agua poco a poco, revolviendo bien para que la mezcla se diluya sin formar grumos. Puede usar un batidor para mezclar, pero asegúrese de no incorporar aire en la mezcla: no debe volverse espumosa.",
      "Vierta la mezcla en una cacerola mediana y añada el sake si lo usa. Coloque la cacerola a fuego medio y remueva constantemente con una espátula mientras la mezcla espesa. En cuanto comience a formar grumos, baje el fuego al mínimo y cocine durante 10 a 15 minutos más, removiendo continuamente, hasta que la mezcla adquiera una consistencia similar a la de un postre cremoso.",
      "Humedezca el interior de un recipiente cuadrado o rectangular (esto es para que el gomadofu se desmolde fácilmente), con una capacidad de unos 750 ml (3 tazas), y vierta la mezcla espesa en él. Alise la superficie con la espátula y coloque el recipiente en la heladera para que se enfríe y solidifique durante 2 a 3 horas.",
      "Desmolde sobre un plato grande y corte en porciones cuadradas con un cuchillo, sumergiendo la hoja en agua caliente entre cada corte.",
    ],
  },
  {
    title: "Misoshiru",
    description: "Sopa de miso",
    portions: "Sirve 2 porciones",
    ingredients: [
      "2 tazas de agua (500ml)",
      "2 cucharadas soperas de pasta de miso (40g)",
      "1/3 de tofu (aproximadamente 100g) cortado en cubos",
      "Opcional: alga wakame cortada en trozos, hongos shitakes hidratados y cortados en trozos, espinaca blanqueda y cortada, etc",
    ],
    image: "https://i.postimg.cc/yYY21DqZ/misoSoup.webp",
    tags: "miso, sopa, tofu",
    link: "./recetas/recipe.html",
    instruction: [
      "Hierva el agua. Separe 2 cuencos y coloque 1 cucharada de pasta de miso en cada uno. Agregue poco a poco el agua caliente a cada cuenco, disolviendo la pasta de miso. Finalmente, agregue los cubos de tofu.",
      "Si está utilizando otros ingredientes, agréguelos también al final.",
      "Tip adicional: Unas gotas de aceite de sésamo pueden darle un sabor muy rico a la sopa de miso.",
    ],
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    ingredients: ["tofu, zanahoria, fécula, porotos"],
    image: "https://example.com/tofu-scramble.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
  {
    title: "Kinoko-Gohan (Arroz con hongos)",
    description: "Arroz con hongos y otros vegetales.",
    portions: "Sirve 4 porciones",
    ingredients: [
      "300 gramos de arroz (preferentemente arroz japonés como koshihikari, arroz fortuna o doble carolina)",
      "50 gramos de zanahoria",
      "100 gramos de hongos shimeji, portobelo o champiñón",
      "2 hongos shitake frescos o hidratados",
      "80 gramos de batata",
      "2 cucharadas soperas de salsa de soja",
    ],
    image: "https://i.postimg.cc/q7vN7bDX/kinoko-gohan.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    ingredients: ["tofu, zanahoria, fécula, porotos"],
    image: "https://example.com/tofu-scramble.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    ingredients: ["tofu, zanahoria, fécula, porotos"],
    image: "https://example.com/tofu-scramble.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    ingredients: ["tofu, zanahoria, fécula, porotos"],
    image: "https://example.com/tofu-scramble.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    ingredients: ["tofu, zanahoria, fécula, porotos"],
    image: "https://example.com/tofu-scramble.jpg",
    tags: "sésamo, tofu, koyasan",
    link: "./recetas/recipe.html",
  },
];
