let data = [
  {
    title: "Goma Dofu (Tofu de sésamo)",
    description: "Tofu de sésamo blanco",
    portions: "Sirve entre 8 y 10 porciones",
    ingredients: [
      "500 ml (1/2 litro) de agua filtrada o de manantial",
      "Un trozo de 5 cm de kombu (opcional)",
      "50 gramos de almidón de kudzu (búscalo en tiendas de alimentos naturales o mercados japoneses, posiblemente bajo el nombre de kuzuko)",
      "70 gramos de pasta de sésamo blanco (puedes usar tahini de Oriente Medio o neri-goma japonés, lo que sea más fácil de encontrar)",
      "1 cucharada de sake (opcional)",
    ],
    image: "https://i.postimg.cc/MGMXQ31y/goma-dofu.jpg",
    tags: "sésamo, tofu, koyasan, gomadofu",
    link: "./recetas/recipe.html",
    instruction: [
      "Ponga el agua y el kombu (si lo usa) en un bol y deje reposar durante al menos 1 hora. Retire el kombu y deséchelo, o resérvelo para otro uso (yo lo agrego al agua cuando cocino legumbres, se dice que ayuda a que sean más fáciles de digerir).",
      "Coloque el almidón de kudzu en un bol mediano para mezclar. Agregue un poco del agua infusionada con kombu y revuelva/triture hasta que esté completamente suave. Añada la pasta de sésamo y luego vierta el resto del agua poco a poco, revolviendo bien para que la mezcla se diluya sin formar grumos. Puede usar un batidor para mezclar, pero asegúrese de no incorporar aire en la mezcla: no debe volverse espumosa.",
      "Vierta la mezcla en una cacerola mediana y añada el sake si lo usa. Coloque la cacerola a fuego medio y remueva constantemente con una espátula mientras la mezcla espesa. En cuanto comience a formar grumos, baje el fuego al mínimo y cocine durante 10 a 15 minutos más, removiendo continuamente, hasta que la mezcla adquiera una consistencia similar a la de un postre cremoso.",
      "Humedezca el interior de un recipiente cuadrado o rectangular (esto es para que el gomadofu se desmolde fácilmente), con una capacidad de unos 750 ml (3 tazas), y vierta la mezcla espesa en él. Alise la superficie con la espátula y coloque el recipiente en la heladera para que se enfríe y solidifique durante 2 a 3 horas.",
      "Desmolde sobre un plato grande y corte en porciones cuadradas con un cuchillo, sumergiendo la hoja en agua caliente entre cada corte.",
    ],
  },
  {
    title: "Misoshiru",
    description: "Sopa de miso",
    portions: "Sirve 2 porciones",
    ingredients: [
      "2 tazas de agua (500ml)",
      "2 cucharadas soperas de pasta de miso (40g)",
      "1/3 de tofu (aproximadamente 100g) cortado en cubos",
      "Opcional: alga wakame cortada en trozos, hongos shitakes hidratados y cortados en trozos, espinaca blanqueda y cortada, etc",
    ],
    image: "https://i.postimg.cc/yYY21DqZ/misoSoup.webp",
    tags: "miso, sopa, tofu",
    link: "./recetas/recipe.html",
    instruction: [
      "Hierva el agua. Separe 2 cuencos y coloque 1 cucharada de pasta de miso en cada uno. Agregue poco a poco el agua caliente a cada cuenco, disolviendo la pasta de miso. Finalmente, agregue los cubos de tofu.",
      "Si está utilizando otros ingredientes, agréguelos también al final.",
      "Tip adicional: Unas gotas de aceite de sésamo pueden darle un sabor muy rico a la sopa de miso.",
    ],
  },
  {
    title: "Ganmodoki",
    description: "Hamburguesitas de tofu",
    portions: "Se hacen aproximadamente 11 hamburguesitas",
    ingredients: [
      "1 paquete de tofu firme (400 gramos)",
      "Media zanahoria",
      "1 cuchara sopera de alga hijiki seca (se puede remplazar por perejil)",
      "4 hongos shitake (frescos o hidratados) o portobellos",
      "3 cucharas soperas de edamame cocido (se puede remplazar por arvejas o porotos de soja)",
      "2-3 cucharas soperas de fécula de papa (o fécula de mandioca)",
      "1 cucharadita de sal",
      "Aceite para freír",
    ],
    image: "https://i.postimg.cc/htrjQXd6/ganmodoki2.webp",
    tags: "hijiki, tofu, koyasan, hamburguesas",
    link: "./recetas/recipe.html",
    instruction: [
      "Envuelve el tofu en papel de cocina y coloca un peso encima para escurrir el agua durante aproximadamente una hora. Mientras tanto, ralla la zanahoria, corta los hongos en trozos pequeños, corta finamente las edamames o soja (o aplasta groseramente las arvejas) y remoja el alga hijiki en 1/2 taza de agua.",
      "Escurre el exceso de agua del tofu y amásalo bien en un bol hasta obtener una textura suave. Añade la sal y la fécula, y mezcla la zanahoria rallada, los hongos, las edamames (o su remplazo) y el alga hijiki remojada (o el perejil cortado finamente).",
      "Calienta el aceite a fuego medio (aproximadamente 150°C/350°F).",
      "Forma pequeñas hamburguesitas con la mezcla y colócalas con cuidado en el aceite.",
      "*No sobrecargues la sartén, ya que bajará la temperatura del aceite.",
      "*Comienza con el fuego bajo y aumenta gradualmente para cocinar las hamburguesas de manera uniforme.",
      "*Si el aceite está demasiado caliente, las hamburguesas pueden romperse.",
      "*Evita tocar las hamburguesas hasta que la superficie esté bien cocida.",
      "Sirve y disfruta con sal, salsa de soja o salsa de soja mezclada con caldo dashi. Para más sabor, añade daikon (rábano) rallado, jengibre rallado o chile.",
    ],
  },
  {
    title: "Kinoko-Gohan (Arroz con hongos)",
    description: "Arroz con hongos y otros vegetales.",
    portions: "Sirve 4 porciones",
    ingredients: [
      "300 gramos de arroz (preferentemente arroz japonés como koshihikari, arroz fortuna o doble carolina)",
      "50 gramos de zanahoria",
      "100 gramos de hongos shimeji, portobello o champiñón",
      "2 hongos shitake frescos o hidratados",
      "80 gramos de batata",
      "2 cucharadas soperas de salsa de soja",
    ],
    image: "https://i.postimg.cc/q7vN7bDX/kinoko-gohan.jpg",
    tags: "arroz, verduras, hongos, salsa de soja, koyasan",
    link: "./recetas/recipe.html",
    instruction: [
      "Primero, lave el arroz hasta que el agua se vuelva un poco transparente (unas 4 veces). Ponga el arroz en un colador y deje que se escurra durante unos 10 minutos.",
      "Coloque el arroz en una cacerola con 400 ml de agua. Deje que el arroz se remoje durante 30 minutos. Esto asegura que el agua penetre hasta el centro de los granos.",
      "Quite y deseche la parte dura al final de los tallos de los hongos shimeji (en el caso de usarlo). Separe los hongos. Quite y deseche los tallos de los hongos shiitake (o portobello), y corte los sombreros en tiras finas de 5 mm de ancho. Coloque los hongos en un colador y enjuáguelos rápidamente, sacudiendo el colador para eliminar el exceso de humedad.",
      "Lave bien la superficie de la batata. Córtela en rodajas de 1 cm de grosor, y luego en dados de 1 cm. Remoje los dados de batata en agua para evitar que se decoloren.",
      "Pele la zanahoria y córtela en trozos de 4 cm. Córtelos a lo largo en tiras finas. Coloque varias tiras una encima de otra y, comenzando por un borde, córtelas en tiras más finas (juliana).",
      "Agregue 2 cucharadas de salsa de soja al arroz en la cacerola. Luego, coloque las verduras y los hongos sobre el arroz. No mezcle. Coloque la tapa en la cacerola y llévela a ebullición a fuego medio.",
      "Cuando hierva y salga vapor vigorosamente por el borde de la tapa, déjelo hervir durante unos 30 segundos. Luego, reduzca el fuego a bajo y déjelo cocer a fuego lento durante 12 minutos. No retire la tapa en ningún momento.",
      "Después de 12 minutos, apague el fuego. Deje la tapa en su lugar y permita que la cacerola repose durante unos 10 minutos. Luego, retire la tapa y use una cuchara de madera humedecida para dar tres grandes vueltas a todo, asegurándose de levantar el arroz del fondo de la cacerola. El plato está listo para servirse.",
    ],
  },
];
